app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /cms

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /cms

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, , _locale: ru }
    requirements:
        _locale: en|ru

hello_name:
    path:     /hello/{_locale}
    defaults: { _controller: AppBundle:Default:hello, , _locale: ru }
    requirements:
        _locale: en|ru
forest:
    path:     /forest/{_locale}
    defaults: { _controller: AppBundle:Default:forest, , _locale: ru }
    requirements:
        _locale: en|ru

news:
    path:     /news_all/{_locale}
    defaults: { _controller: AppBundle:News:news, , _locale: ru }
    requirements:
        _locale: en|ru

news_list:
    path:     /news_list/{_locale}
    defaults: { _controller: AppBundle:News:newsList, , _locale: ru }
    requirements:
        _locale: en|ru

callback_list:
    path:     callback_list/{_locale}
    defaults: { _controller: AppBundle:Callback:list, , _locale: ru }
    requirements:
        _locale: en|ru

callback_form:
    path:     callback/{_locale}
    defaults: { _controller: AppBundle:Callback:callback, , _locale: ru }
    requirements:
        _locale: en|ru

fos_user_security_login:
    path:     login/{_locale}
    defaults: { _controller: FOSUserBundle:Security:login, , _locale: ru }
    requirements:
        _locale: en|ru