# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    sender: debug@tradedealer.ru
    recipient: a.malozemov@tradedealer.ru

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Callback, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Категории, label: Заявки }

    app.message_service:
        class: AppBundle\Service\MessageService
        arguments: ['@mailer', '@twig', '%sender%', '%recipient%']

    app.database_service:
        class: AppBundle\Service\DbService
        arguments: ['@doctrine.orm.entity_manager']