# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    sender: debug@tradedealer.ru
    recipient: a.malozemov@tradedealer.ru

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    admin.category:
        class: AppBundle\Admin\CallbackAdmin
        arguments: [~, AppBundle\Entity\Callback, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Категории, label: Заявки }

    manager.category:
        class: AppBundle\Admin\UsersAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Категории, label: Пользователи}

    news.category:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Категории, label: Новости}

    app.message_service:
        class: AppBundle\Service\MessageService
        arguments: ['@mailer', '@twig', '%sender%', '%recipient%']

    app.database_service_callback:
        class: AppBundle\Service\CallbackService
        arguments: ['@doctrine.orm.entity_manager']

    app.database_service_news:
        class: AppBundle\Service\NewsService
        arguments: ['@doctrine.orm.entity_manager']

    app.image_upload:
        class: AppBundle\Service\ImageService
        arguments: ['@doctrine.orm.entity_manager', '@liip_imagine.cache.manager']
