# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    sender: debug@tradedealer.ru
    recipient: a.malozemov@tradedealer.ru

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    admin.category:
        class: AppBundle\Admin\Admin
        arguments: [~, AppBundle\Entity\Callback, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Категории, label: Заявки }

    manager.catgory:
        class: AppBundle\Admin\Users
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Категории, label: Пользователи}

    app.message_service:
        class: AppBundle\Service\MessageService
        arguments: ['@mailer', '@twig', '%sender%', '%recipient%']

    app.database_service:
        class: AppBundle\Service\CallbackService
        arguments: ['@doctrine.orm.entity_manager']