AppBundleBundle\Entity\News:
    type: entity
    repositoryClass: AppBundle\Entity\Repositories\ImageRepository
    table: news
    fields:
        image:
            type:         string
            length:       255

#    updated:
#        type:         datetime
#        nullable:     true


        # ... other fields ...
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]